[mypy]
python_version = 3.10
warn_unused_configs = True
show_error_codes = True
ignore_missing_imports = True
follow_imports = skip
implicit_reexport = True
disable_error_code = annotation-unchecked

[mypy-requests.*]
ignore_missing_imports = True
